export const CITIES = [
    "Afghanistan",
    "Badakhshan",
    "Badghis",
    "Baghlan",
    "Balkh",
    "Bamyan",
    "Daykundi",
    "Farah",
    "Faryab",
    "Ghazni",
    "Ghor",
    "Helmand",
    "Herat",
    "Jowzjan",
    "Kabul",
    "Kandahar",
    "Kapisa",
    "Khost",
    "Kunar",
    "Kunduz",
    "Laghman",
    "Logar",
    "Nangarhar",
    "Nimruz",
    "Nuristan",
    "Paktia",
    "Paktika",
    "Panjshir",
    "Parwan",
    "Samangan",
    "Sar-e Pol",
    "Takhar",
    "Uruzgan",
    "Wardak",
    "Zabul",
    "Albania",
    "Berat",
    "Dibër",
    "Durrës",
    "Elbasan",
    "Fier",
    "Gjirokastër",
    "Korçë",
    "Kukës",
    "Lezhë",
    "Shkodër",
    "Tirana",
    "Vlorë",
    "Algeria",
    "Chlef",
    "Laghouat",
    "Oum El Bouaghi",
    "Batna",
    "Béjaïa",
    "Biskra",
    "Béchar",
    "Blida",
    "Bouïra",
    "Tamanrasset",
    "Tébessa",
    "Tlemcen",
    "Tiaret",
    "Tizi Ouzou",
    "Algiers",
    "Djelfa",
    "Jijel",
    "Sétif",
    "Saïda",
    "Skikda",
    "Sidi Bel Abbès",
    "Annaba",
    "Guelma",
    "Constantine",
    "Médéa",
    "Mostaganem",
    "M'Sila",
    "Mascara",
    "Ouargla",
    "Oran",
    "El Bayadh",
    "Illizi",
    "Bordj Bou Arréridj",
    "Boumerdès",
    "American Samoa",
    "Tutuila",
    "Aunuʻu",
    "Ofu",
    "Olosega",
    "Taʻū",
    "Swains",
    "Rose",
    "Andorra",
    "Andorra la Vella",
    "Canillo",
    "Encamp",
    "Escaldes-Engordany",
    "La Massana[1]",
    "Ordino",
    "Sant Julià de Lòria",
    "Angola",
    "Bengo",
    "Benguela",
    "Bié",
    "Cabinda",
    "Cuando Cubango",
    "Cuanza Norte",
    "Cuanza Sul",
    "Cunene",
    "Huambo",
    "Huíla",
    "Luanda",
    "Lunda Norte",
    "Lunda Sul",
    "Malanje",
    "Moxico",
    "Namibe",
    "Uíge",
    "Zaire",
    "Anguilla",
    "Antigua",
    "Saint George",
    "Saint John",
    "Saint Mary",
    "Saint Paul",
    "Saint Peter",
    "Saint Philip",
    "Barbuda",
    "Redonda",
    "Argentina",
    "Autonomous City of Buenos Aires",
    "Buenos Aires",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego, Antártida e Islas del Atlántico Sur",
    "Tucumán",
    "Armenia",
    "Aragatsotn",
    "Ararat",
    "Armavir",
    "Gegharkunik",
    "Kotayk",
    "Lori",
    "Shirak",
    "Syunik",
    "Tavush",
    "Vayots Dzor",
    "Yerevan",
    "Aruba",
    "Noord",
    "Oranjestad West",
    "Oranjestad Oost",
    "Paradera",
    "San Nicolas Noord",
    "San Nicolas Zuid",
    "Savaneta",
    "Australia",
    "Australian Capital Territory",
    "New South Wales",
    "Northern Territory",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia",
    "Austria",
    "Burgenland",
    "Kaernten",
    "Niederoesterreich",
    "Oberoesterreich",
    "Salzburg",
    "Steiermark",
    "Tirol",
    "Vorarlberg",
    "Wien",
    "Azerbaijan",
    "Bahrain",
    "Capital",
    "Muharraq",
    "Northern",
    "Southern",
    "Bangladesh",
    "Barisal Division",
    "Chittagong Division",
    "Dhaka Division",
    "Khulna Division",
    "Mymensingh Division",
    "Rajshahi Division",
    "Rangpur Division",
    "Sylhet Division",
    "Barbados",
    "Christ Church",
    "St. Andrew",
    "St. George",
    "St. James",
    "St. John",
    "St. Joseph",
    "St. Lucy",
    "St. Michael",
    "St. Peter",
    "St. Philip",
    "St. Thomas",
    "Belarus",
    "Belgium",
    "West Flanders",
    "East Flanders",
    "Antwerp",
    "Limburg",
    "Flemish Brabant",
    "None",
    "Walloon Brabant",
    "Hainaut",
    "Luxem­bourg",
    "Namur",
    "Liège/Lüttich",
    "Belize",
    "Cayo",
    "Corozal",
    "Orange Walk",
    "Stann Creek",
    "Toledo",
    "Benin",
    "Alibori",
    "Atakora",
    "Atlantique",
    "Borgou",
    "Collines",
    "Kouffo",
    "Donga",
    "Littoral",
    "Mono",
    "Ouémé",
    "Plateau",
    "Zou",
    "Bermuda",
    "Bhutan",
    "Bumthang",
    "Chukha",
    "Dagana",
    "Gasa",
    "Haa",
    "Lhuntse",
    "Mongar",
    "Paro",
    "Pemagatshel",
    "Punakha",
    "Samdrup Jongkhar",
    "Samtse",
    "Sarpang",
    "Thimphu",
    "Trashigang",
    "Trashiyangtse",
    "Trongsa",
    "Tsirang",
    "Wangdue Phodrang",
    "Zhemgang",
    "Bolivia",
    "Beni",
    "Chuquisaca",
    "Cochabamba",
    "La Paz",
    "Oruro",
    "Pando",
    "Potosí",
    "Tarija",
    "Bosnia and Herzegovina",
    "Posavina Canton",
    "Tuzla Canton",
    "Zenica-Doboj Canton",
    "Bosnian-Podrinje Canton Goražde",
    "Central Bosnia Canton",
    "Herzegovina-Neretva Canton",
    "West Herzegovina Canton",
    "Sarajevo Canton",
    "Canton 10",
    "Botswana",
    "Southern District",
    "South-East District",
    "Kweneng District",
    "Kgatleng District",
    "Central District",
    "North-East District",
    "Ngamiland District",
    "Chobe District",
    "Ghanzi District",
    "Kgalagadi District",
    "Brazil",
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Distrito Federal",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins",
    "British Indian Ocean Territory",
    "Peros Banhos",
    "Salomon Islands",
    "Nelsons Island",
    "Three Brothers",
    "Eagle Islands",
    "Danger Island",
    "Egmont Islands",
    "Diego Garcia",
    "British Virgin Islands",
    "Anegada",
    "Jost Van Dyke",
    "Tortola",
    "Virgin Gorda",
    "Other Islands",
    "Brunei",
    "Brunei-Muara",
    "Belait",
    "Tutong",
    "Temburong",
    "Bulgaria",
    "Blagoevgrad",
    "Burgas",
    "Dobrich",
    "Gabrovo",
    "Haskovo",
    "Kardzhali",
    "Kyustendil",
    "Lovech",
    "Montana",
    "Pazardzhik",
    "Pernik",
    "Pleven",
    "Plovdiv",
    "Razgrad",
    "Ruse",
    "Shumen",
    "Silistra",
    "Sliven",
    "Smolyan",
    "Sofia City",
    "Sofia Province",
    "Stara Zagora",
    "Targovishte",
    "Varna",
    "Veliko Tarnovo",
    "Vidin",
    "Vratsa",
    "Yambol",
    "Burkina Faso",
    "Boucle du Mouhoun",
    "Cascades",
    "Centre",
    "Centre-Est",
    "Centre-Nord",
    "Centre-Ouest",
    "Centre-Sud",
    "Est",
    "Hauts-Bassins",
    "Nord",
    "Plateau-Central",
    "Sahel",
    "Sud-Ouest",
    "Burma Myanmar",
    "Ayeyarwady Region",
    "Bago Region",
    "Chin State",
    "Kachin State",
    "Kayah State",
    "Kayin State",
    "Magway Region",
    "Mandalay Region",
    "Mon State",
    "Naypyidaw Union Territory",
    "Rakhine State",
    "Sagaing Region",
    "Shan State",
    "Tanintharyi Region",
    "Yangon Region",
    "Burundi",
    "Cankuzo",
    "Gitega",
    "Rutana",
    "Ruyigi",
    "Karuzi",
    "Kayanza",
    "Kirundo",
    "Muyinga",
    "Ngozi",
    "Bururi",
    "Makamba",
    "Rumonge",
    "Bubanza",
    "Bujumbura Mairie",
    "Bujumbura Rural",
    "Cibitoke",
    "Muramvya",
    "Mwaro",
    "Cambodia",
    "Banteay Meanchey",
    "Battambang",
    "Kampong Cham",
    "Kampong Chhnang",
    "Kampong Speu",
    "Kampong Thom",
    "Kampot",
    "Kandal",
    "Kep",
    "Koh Kong",
    "Kratié",
    "Mondulkiri",
    "Oddar Meanchey",
    "Pailin",
    "Phnom Penh",
    "Preah Sihanouk",
    "Preah Vihear",
    "Prey Veng",
    "Pursat",
    "Ratanakiri",
    "Siem Reap",
    "Stung Treng",
    "Svay Rieng",
    "Takéo",
    "Tboung Khmum",
    "Cameroon",
    "Adamawa",
    "East",
    "Far North",
    "North",
    "Northwest",
    "South",
    "Southwest",
    "West",
    "Canada",
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon Territory",
    "Cape Verde",
    "Tarrafal",
    "São Miguel",
    "São Salvador do Mundo",
    "São Domingos",
    "Praia",
    "Ribeira Grande de Santiago",
    "São Lourenço dos Órgãos",
    "Brava",
    "São Filipe",
    "Santa Catarina do Fogo",
    "Mosteiros",
    "Maio",
    "Boa Vista",
    "Sal",
    "Ribeira Brava",
    "Tarrafal de São Nicolau",
    "São Vicente",
    "Porto Novo",
    "Ribeira Grande",
    "Paul",
    "Cayman Islands",
    "Bodden Town",
    "Cayman Brac",
    "East End",
    "George Town",
    "Little Cayman",
    "North Side",
    "West Bay",
    "Central African Republic",
    "Bangui",
    "Mbomou",
    "Basse-Kotto",
    "Kémo",
    "Nana-Mambéré",
    "Ouham",
    "Sangha-Mbaéré",
    "Lobaye",
    "Ombella-M'Poko",
    "Ouham-Pendé",
    "Haut-Mbomou",
    "Ouaka",
    "Haute-Kotto",
    "Bamingui-Bangoran",
    "Vakaga",
    "Nana-Grébizi",
    "Mambéré-Kadéï",
    "Mambéré",
    "Lim-Pendé",
    "Ouham-Fafa",
    "Chad",
    "Batha",
    "Chari-Baguirmi",
    "Hadjer-Lamis",
    "Wadi Fira",
    "Bahr el Gazel",
    "Borkou",
    "Ennedi-Est",
    "Ennedi-Ouest",
    "Guéra",
    "Kanem",
    "Lac",
    "Logone Occidental",
    "Logone Oriental",
    "Mandoul",
    "Mayo-Kebbi Est",
    "Mayo-Kebbi Ouest",
    "Moyen-Chari",
    "Ouaddaï",
    "Salamat",
    "Sila",
    "Tandjilé",
    "Tibesti",
    "N'Djamena",
    "Chile",
    "Arica and Parinacota",
    "Tarapacá",
    "Antofagasta",
    "Atacama",
    "Coquimbo",
    "Valparaíso",
    "Metropolitan",
    "O'Higgins",
    "Maule",
    "Ñuble",
    "Biobío",
    "Araucanía",
    "Los Ríos",
    "Los Lagos",
    "Aysén",
    "Magallanes",
    "China",
    "Hebei",
    "Shanxi",
    "Liaoning",
    "Jilin",
    "Heilongjiang",
    "Jiangsu",
    "Zhejiang",
    "Anhui",
    "Fujian",
    "Jiangxi",
    "Shandong",
    "Henan",
    "Hubei",
    "Hunan",
    "Guangdong",
    "Hainan",
    "Sichuan",
    "Guizhou",
    "Yunnan",
    "Shaanxi",
    "Gansu",
    "Qinghai",
    "Taiwan",
    "Colombia",
    "Capital District",
    "Antioquia",
    "Arauca",
    "Atlántico",
    "Bolívar",
    "Boyacá",
    "Caldas",
    "Caquetá",
    "Casanare",
    "Cauca",
    "Cesar",
    "Chocó",
    "Cundinamarca",
    "Guainía",
    "Guaviare",
    "Huila",
    "La Guajira",
    "Magdalena",
    "Meta",
    "Nariño",
    "Norte de Santander",
    "Putumayo",
    "Quindío",
    "Risaralda",
    "San Andrés y Providencia",
    "Santander",
    "Sucre",
    "Tolima",
    "Valle del Cauca",
    "Vaupés",
    "Vichada",
    "Comoros",
    "Anjouan",
    "Grande Comore",
    "Mohéli",
    "Cook Islands",
    "Aitutaki",
    "Atiu",
    "Mangaia",
    "Manihiki",
    "Mauke",
    "Mitiaro",
    "Palmerston",
    "Penrhyn",
    "Pukapuka",
    "Rakahanga",
    "Costa Rica",
    "Alajuela",
    "Cartago",
    "Guanacaste",
    "Heredia",
    "Limón",
    "Puntarenas",
    "San José",
    "Côte dIvoire",
    "Abidjan",
    "Bas-Sassandra",
    "Comoé",
    "Denguélé",
    "Gôh-Djiboua",
    "Lacs",
    "Lagunes",
    "Montagnes",
    "Sassandra-Marahoué",
    "Savanes",
    "Vallée du Bandama",
    "Woroba",
    "Yamoussoukro",
    "Zanzan",
    "Croatia",
    "Križevci",
    "Požega",
    "Syrmia",
    "Varaždin",
    "Virovitica",
    "Zagreb",
    "Littoral/Rijeka",
    "Bjelovar",
    "Cuba",
    "Pinar del Río",
    "Artemisa",
    "La Habana",
    "Mayabeque",
    "Matanzas",
    "Cienfuegos",
    "Villa Clara",
    "Sancti Spíritus",
    "Ciego de Ávila",
    "Camagüey",
    "Las Tunas",
    "Granma",
    "Holguín",
    "Santiago de Cuba",
    "Guantánamo",
    "Isla de la Juventud",
    "Cyprus",
    "Famagusta",
    "Kyrenia",
    "Larnaca",
    "Limassol",
    "Nicosia",
    "Paphos",
    "Czech Republic",
    "Prague",
    "Central Bohemian",
    "South Bohemian",
    "Plzeň",
    "Karlovy Vary",
    "Ústí nad Labem",
    "Liberec",
    "Hradec Králové",
    "Pardubice",
    "Vysočina",
    "South Moravian",
    "Olomouc",
    "Zlín",
    "Moravian-Silesian",
    "Democratic Republic of Congo",
    "Kongo Central",
    "Kwango",
    "Kwilu",
    "Mai-Ndombe",
    "Kasaï",
    "Kasaï-Central",
    "Kasaï-Oriental",
    "Lomami",
    "Sankuru",
    "Maniema",
    "South Kivu",
    "North Kivu",
    "Ituri",
    "Haut-Uele",
    "Tshopo",
    "Bas-Uele",
    "Nord-Ubangi",
    "Mongala",
    "Sud-Ubangi",
    "Équateur",
    "Tshuapa",
    "Tanganyika",
    "Haut-Lomami",
    "Lualaba",
    "Haut-Katanga",
    "Denmark",
    "Region Hovedstaden",
    "Region Midtjylland",
    "Region Nordjylland",
    "Region Sjælland",
    "Region Syddanmark",
    "Djibouti",
    "Djibouti Region",
    "Ali Sabieh Region",
    "Arta Region",
    "Dikhil Region",
    "Tadjourah Region",
    "Obock Region",
    "Dominica",
    "Saint Andrew",
    "Saint David",
    "Saint Joseph",
    "Saint Luke",
    "Saint Mark",
    "Saint Patrick",
    "Dominican Republic",
    "Azua",
    "Baoruco",
    "Barahona",
    "Dajabón",
    "Duarte",
    "El Seibo",
    "Elías Piña",
    "Espaillat",
    "Hato Mayor",
    "Hermanas Mirabal",
    "Independencia",
    "La Altagracia",
    "La Romana",
    "La Vega",
    "María Trinidad Sánchez",
    "Monseñor Nouel",
    "Monte Cristi",
    "Monte Plata",
    "Pedernales",
    "Peravia",
    "Puerto Plata",
    "Samaná",
    "San Cristóbal",
    "San José de Ocoa",
    "San Pedro de Macorís",
    "Sánchez Ramírez",
    "Santiago",
    "Santiago Rodríguez",
    "Santo Domingo",
    "Valverde",
    "Distrito Nacional",
    "Ecuador",
    "Azuay",
    "Cañar",
    "Carchi",
    "Chimborazo",
    "Cotopaxi",
    "El Oro",
    "Esmeraldas",
    "Galápagos",
    "Guayas",
    "Imbabura",
    "Loja",
    "Manabí",
    "Morona Santiago",
    "Napo",
    "Orellana",
    "Pastaza",
    "Pichincha",
    "Santa Elena",
    "Santo Domingo de los Tsáchilas",
    "Sucumbíos",
    "Tungurahua",
    "Zamora Chinchipe",
    "Egypt",
    "Alexandria",
    "Aswan",
    "Asyut",
    "Beheira",
    "Beni Suef",
    "Cairo",
    "Dakahlia",
    "Damietta",
    "Faiyum",
    "Gharbia",
    "Giza",
    "Ismailia",
    "Kafr El Sheikh",
    "Luxor",
    "Matrouh",
    "Minya",
    "Monufia",
    "New Valley",
    "North Sinai",
    "Port Said[23]",
    "Qalyubia",
    "Qena",
    "Red Sea",
    "Sharqia",
    "Sohag",
    "South Sinai",
    "Suez",
    "El Salvador",
    "Ahuachapán",
    "Cabañas",
    "Chalatenango",
    "Cuscatlán",
    "La Libertad",
    "La Unión",
    "Morazán",
    "San Miguel",
    "San Salvador",
    "San Vicente",
    "Santa Ana",
    "Sonsonate",
    "Usulután",
    "Equatorial Guinea",
    "Annobón",
    "Bioko Norte",
    "Bioko Sur",
    "Centro Sur",
    "Kié-Ntem",
    "Litoral",
    "Wele-Nzas",
    "Djibloho",
    "Eritrea",
    "Maekel Region",
    "Anseba Region",
    "Gash-Barka Region",
    "Debub Region",
    "Northern Red Sea Region",
    "Southern Red Sea Region",
    "Estonia",
    "Hiiu County",
    "Ida-Viru County",
    "Jõgeva County",
    "Järva County",
    "Lääne County",
    "Lääne-Viru County",
    "Põlva County",
    "Pärnu County",
    "Rapla County",
    "Saare County",
    "Tartu County",
    "Valga County",
    "Viljandi County",
    "Võru County",
    "Ethiopia",
    "Addis Ababa",
    "Afar Region",
    "Amhara Region",
    "Benishangul-Gumuz Region",
    "Central Ethiopia Regional State",
    "Dire Dawa",
    "Gambela Region",
    "Harari Region",
    "Oromia Region",
    "Sidama Region",
    "Somali Region",
    "South Ethiopia Regional State",
    "South West Ethiopia Peoples' Region",
    "Tigray Region",
    "Falkland Islands",
    "Stanley",
    "Camp",
    "Faroe Islands",
    "Eysturoy region",
    "Norðoyar region",
    "Sandoy region",
    "Streymoy region",
    "Suðuroy region",
    "Vágar region",
    "Federated States of Micronesia",
    "Chuuk",
    "Kosrae",
    "Pohnpei",
    "Yap",
    "Fiji",
    "Naitasiri",
    "Namosi",
    "Rewa",
    "Serua",
    "Tailevu",
    "Bua",
    "Cakaudrove",
    "Macuata",
    "Kadavu",
    "Lau",
    "Lomaiviti",
    "Ba",
    "Nadroga-Navosa",
    "Ra",
    "Rotuma",
    "Finland",
    "Lapland",
    "North Ostrobothnia",
    "Kainuu",
    "North Karelia",
    "North Savo",
    "South Savo",
    "South Karelia",
    "Central Finland",
    "South Ostrobothnia",
    "Ostrobothnia",
    "Central Ostrobothnia",
    "Pirkanmaa",
    "Satakunta",
    "Päijät-Häme",
    "Kanta-Häme",
    "Kymenlaakso",
    "Uusimaa",
    "Southwest Finland",
    "Åland",
    "France",
    "Alsace",
    "Aquitaine",
    "Auvergne",
    "Brittany",
    "Burgundy",
    "Centre-Val de Loire[4]",
    "Champagne-Ardenne",
    "Corsica",
    "Franche-Comté",
    "Île-de-France",
    "Languedoc-Roussillon",
    "Limousin",
    "Lorraine",
    "Lower Normandy",
    "Midi-Pyrénées",
    "Nord-Pas-de-Calais",
    "Pays de la Loire",
    "Picardy",
    "Poitou-Charentes",
    "Provence-Alpes-Côte d'Azur (PACA)",
    "Rhône-Alpes",
    "Upper Normandy",
    "French Guiana",
    "Cayenne",
    "Saint-Laurent-du-Maroni",
    "French Polynesia",
    "Windward Islands",
    "Leeward Islands",
    "Marquesas Islands",
    "Austral Islands",
    "Tuamotu-Gambier",
    "Gabon",
    "Estuaire",
    "Haut-Ogooué",
    "Moyen-Ogooué",
    "Ngounié",
    "Nyanga",
    "Ogooué-Ivindo",
    "Ogooué-Lolo",
    "Ogooué-Maritime",
    "Woleu-Ntem",
    "Georgia",
    "Tbilisi",
    "Imereti",
    "Ajaria",
    "Kvemo Kartli",
    "Samegrelo and Zemo Svaneti",
    "Kakheti",
    "Shida Kartli",
    "Abkhazia",
    "Samtskhe-Javakheti",
    "Guria",
    "Mtskheta-Mtianeti",
    "Racha-Lechkhumi and Kvemo Svaneti",
    "Germany",
    "Baden-Württemberg",
    "Bavaria",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hesse",
    "Lower Saxony",
    "Mecklenburg-Vorpommern",
    "North Rhine-Westphalia",
    "Rhineland-Palatinate",
    "Saarland",
    "Saxony",
    "Saxony-Anhalt",
    "Schleswig-Holstein",
    "Thuringia",
    "Ghana",
    "Ashanti",
    "Brong-Ahafo",
    "Central",
    "Eastern",
    "Greater Accra",
    "Upper East",
    "Upper West",
    "Volta",
    "Western",
    "Gibraltar",
    "Eastside",
    "North District",
    "Reclamation Areas",
    "Sandpits Area",
    "South District",
    "Town Area",
    "Upper Town",
    "Greece",
    "Attica",
    "Central Greece",
    "Central Macedonia",
    "Crete",
    "Eastern Macedonia and Thrace",
    "Epirus",
    "Ionian Islands",
    "North Aegean",
    "Peloponnese",
    "South Aegean",
    "Thessaly",
    "Western Greece",
    "Western Macedonia",
    "Monastic community of Mount Athos",
    "Greenland",
    "Avannaata",
    "Kujalleq",
    "Qeqertalik",
    "Qeqqata",
    "Sermersooq",
    "Grenada",
    "Guadeloupe",
    "Basse-Terre",
    "Pointe-à-Pitre",
    "Guam",
    "Agana Heights",
    "Asan-Maina",
    "Barrigada",
    "Chalan Pago-Ordot",
    "Dededo",
    "Hågat",
    "Hagåtña",
    "Humåtak",
    "Inalåhan",
    "Malesso'",
    "Mangilao",
    "Mongmong-Toto-Maite",
    "Piti",
    "Sånta Rita-Sumai",
    "Sinajana",
    "Talo'fo'fo",
    "Tamuning",
    "Yigo",
    "Guatemala",
    "Alta Verapaz",
    "Baja Verapaz",
    "Chimaltenango",
    "Chiquimula",
    "El Progreso",
    "Escuintla",
    "Guatemala Department",
    "Huehuetenango",
    "Izabal",
    "Jalapa",
    "Jutiapa",
    "Petén",
    "Quetzaltenango",
    "Quiché",
    "Retalhuleu",
    "Sacatepéquez",
    "San Marcos",
    "Santa Rosa",
    "Sololá",
    "Suchitepéquez",
    "Totonicapán",
    "Zacapa",
    "Guinea",
    "Guinea-Bissau",
    "Bafatá",
    "Biombo",
    "Bissau",
    "Bolama",
    "Cacheu",
    "Gabu",
    "Oio",
    "Quinara",
    "Tombali",
    "Guyana",
    "Barima-Waini",
    "Pomeroon-Supenaam",
    "Essequibo Islands-West Demerara",
    "Demerara-Mahaica",
    "Mahaica-Berbice",
    "East Berbice-Corentyne",
    "Cuyuni-Mazaruni",
    "Potaro-Siparuni",
    "Upper Takutu-Upper Essequibo",
    "Upper Demerara-Berbice",
    "Haiti",
    "Artibonite",
    "Grand'Anse",
    "Nippes",
    "Nord-Est",
    "Nord-Ouest",
    "Ouest",
    "Sud-Est",
    "Sud",
    "Honduras",
    "Atlántida",
    "Choluteca",
    "Colón",
    "Comayagua",
    "Copán",
    "Cortés",
    "El Paraíso",
    "Francisco Morazán",
    "Gracias a Dios",
    "Intibucá",
    "Islas de la Bahía",
    "Lempira",
    "Ocotepeque",
    "Olancho",
    "Santa Bárbara",
    "Valle",
    "Yoro",
    "Hong Kong",
    "Hungary",
    "Baranya",
    "Bács-Kiskun",
    "Békés",
    "Borsod-Abaúj-Zemplén",
    "Budapest",
    "Csongrád-Csanád",
    "Fejér",
    "Győr-Moson-Sopron",
    "Hajdú-Bihar",
    "Heves",
    "Jász-Nagykun-Szolnok",
    "Komárom-Esztergom",
    "Nógrád",
    "Pest",
    "Somogy",
    "Szabolcs-Szatmár-Bereg",
    "Tolna",
    "Vas",
    "Veszprém",
    "Zala",
    "Iceland",
    "Capital Region",
    "Southern Peninsula",
    "Western Region",
    "Westfjords",
    "Northwestern Region",
    "Northeastern Region",
    "Eastern Region",
    "Southern Region",
    "India",
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Orissa",
    "Pondicherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Tripura",
    "Uttaranchal",
    "Uttar Pradesh",
    "West Bengal",
    "Indonesia",
    "Name[3][4]",
    "Aceh",
    "Bali",
    "Bangka Belitung Islands",
    "Banten",
    "Bengkulu",
    "Central Java",
    "Central Kalimantan",
    "Central Papua",
    "Central Sulawesi",
    "East Java",
    "East Kalimantan",
    "East Nusa Tenggara",
    "Gorontalo",
    "Highland Papua",
    "Special Capital Region of Jakarta",
    "Jambi",
    "Lampung",
    "Maluku",
    "North Kalimantan",
    "North Maluku",
    "North Sulawesi",
    "North Sumatra",
    "Papua",
    "Riau",
    "Riau Islands",
    "Southeast Sulawesi",
    "South Kalimantan",
    "South Papua",
    "South Sulawesi",
    "South Sumatra",
    "Southwest Papua",
    "West Java",
    "West Kalimantan",
    "West Nusa Tenggara",
    "West Papua",
    "West Sulawesi",
    "West Sumatra",
    "Special Region of Yogyakarta",
    "Iran",
    "Khuzestan province",
    "Astarabad (Gorgan)",
    "Damavand",
    "Gerrus (Bijar)",
    "Gilan (Rasht)",
    "Golpayegan, Kamareh, and Khansar",
    "Hamadan",
    "Iraq (Arak)",
    "Isfahan",
    "Kashan",
    "Khamseh (Zanjan)",
    "Kermanshahan",
    "Kurdistan (Sanandaj)",
    "Luristan (Borujerd)",
    "Malayer",
    "Mazandaran (Sari)",
    "Qazvin",
    "Qom",
    "Saveh",
    "Semnan and Damghan",
    "Shahrud and Bastam",
    "Yazd",
    "Iraq",
    "Al-Anbar",
    "Babil",
    "Baghdad",
    "Basra",
    "Dhi Qar",
    "Al-Qādisiyyah",
    "Diyala",
    "Duhok (Dahūk) (IKR) a.k.a. Dihok",
    "Erbil (IKR) a.k.a. Hewlêr",
    "Karbala",
    "Kirkuk",
    "Maysan",
    "Muthanna",
    "Najaf",
    "Ninawa",
    "Salah Al-Din",
    "Sulaymaniyah (IKR) (With Halabja) a.k.a. Silêmanî",
    "Wasit",
    "Ireland",
    "Dublin City",
    "Dún Laoghaire–Rathdown County",
    "Fingal County",
    "Kildare County",
    "Laois County",
    "Longford County",
    "Louth County",
    "Meath County",
    "Offaly County",
    "South Dublin County",
    "Westmeath County",
    "Wicklow County",
    "Cavan County",
    "Donegal County",
    "Galway City",
    "Galway County",
    "Leitrim County",
    "Mayo County",
    "Monaghan County",
    "Roscommon County",
    "Sligo County",
    "Carlow County",
    "Clare County",
    "Cork City",
    "Cork County",
    "Kerry County",
    "Kilkenny County",
    "Limerick City and County",
    "Tipperary County",
    "Waterford City and County",
    "Wexford County",
    "Israel",
    "Jerusalem",
    "Tzfat",
    "Kinneret",
    "Yizre'el",
    "Akko",
    "Golan",
    "Haifa",
    "Hadera",
    "Sharon",
    "Petah Tikva",
    "Ramla",
    "Rehovot",
    "Tel Aviv",
    "Ashkelon",
    "Be'er Sheva",
    "Italy",
    "Abruzzo",
    "Aosta Valley",
    "Puglia",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Friuli-Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardy",
    "Marche",
    "Molise",
    "Piedmont",
    "Sardinia",
    "Sicily",
    "Trentino-South Tyrol",
    "Tuscany",
    "Umbria",
    "Veneto",
    "Jamaica",
    "Hanover",
    "Saint Elizabeth",
    "Saint James",
    "Trelawny",
    "Westmoreland",
    "Clarendon",
    "Manchester",
    "Saint Ann",
    "Saint Catherine",
    "Kingston Parish",
    "Portland",
    "Saint Thomas",
    "Japan",
    "Aichi",
    "Akita",
    "Aomori",
    "Chiba",
    "Ehime",
    "Fukui",
    "Fukuoka",
    "Fukushima",
    "Gifu",
    "Gunma",
    "Hiroshima",
    "Hokkaido",
    "Hyōgo",
    "Ibaraki",
    "Ishikawa",
    "Iwate",
    "Kagawa",
    "Kagoshima",
    "Kanagawa",
    "Kōchi",
    "Kumamoto",
    "Kyōto",
    "Mie",
    "Miyagi",
    "Miyazaki",
    "Nagano",
    "Nagasaki",
    "Nara",
    "Niigata",
    "Ōita",
    "Okayama",
    "Okinawa",
    "Ōsaka",
    "Saga",
    "Saitama",
    "Shiga",
    "Shimane",
    "Shizuoka",
    "Tochigi",
    "Tokushima",
    "Tōkyō",
    "Tottori",
    "Toyama",
    "Wakayama",
    "Yamagata",
    "Yamaguchi",
    "Yamanashi",
    "Jordan",
    "Irbid",
    "Ajloun",
    "Jerash",
    "Mafraq",
    "Balqa",
    "Amman",
    "Zarqa",
    "Madaba",
    "Karak",
    "Tafilah",
    "Ma'an",
    "Aqaba",
    "Kazakhstan",
    "Abai Region",
    "Akmola Region",
    "Aktobe Region",
    "Almaty",
    "Almaty Region",
    "Astana",
    "Atyrau Region",
    "Baikonur",
    "East Kazakhstan Region",
    "Jambyl Region",
    "Jetisu Region",
    "Karaganda Region",
    "Kostanay Region",
    "Kyzylorda Region",
    "Mangystau Region",
    "North Kazakhstan Region",
    "Pavlodar Region",
    "Shymkent",
    "Turkistan Region",
    "Ulytau Region",
    "West Kazakhstan Region",
    "Kenya",
    "Mombasa",
    "Kwale",
    "Kilifi",
    "Tana River",
    "Lamu",
    "Taita–Taveta",
    "Garissa",
    "Wajir",
    "Mandera",
    "Marsabit",
    "Isiolo",
    "Meru",
    "Tharaka-Nithi",
    "Embu",
    "Kitui",
    "Machakos",
    "Makueni",
    "Nyandarua",
    "Nyeri",
    "Kirinyaga",
    "Murang'a",
    "Kiambu",
    "Turkana",
    "West Pokot",
    "Samburu",
    "Trans-Nzoia",
    "Uasin Gishu",
    "Elgeyo-Marakwet",
    "Nandi",
    "Baringo",
    "Laikipia",
    "Nakuru",
    "Narok",
    "Kajiado",
    "Kericho",
    "Bomet",
    "Kakamega",
    "Vihiga",
    "Bungoma",
    "Busia",
    "Siaya",
    "Kisumu",
    "Homa Bay",
    "Migori",
    "Kisii",
    "Nyamira",
    "Nairobi",
    "Kiribati",
    "Banaba Island",
    "Gilbert Islands",
    "Line Islands",
    "Phoenix Islands",
    "Kosovo",
    "District of Ferizaj",
    "District of Gjakova",
    "District of Gjilan",
    "District of Mitrovica",
    "District of Peja",
    "District of Pristina",
    "District of Prizren",
    "Kuwait",
    "Ahmadi Governorate",
    "Al-Asimah Governorate",
    "Farwaniya Governorate",
    "Hawalli Governorate",
    "Jahra Governorate",
    "Mubarak Al-Kabeer Governorate",
    "Kyrgyzstan",
    "Bishkek City",
    "Batken Region",
    "Chüy Region",
    "Jalal-Abad Region",
    "Naryn Region",
    "Osh Region",
    "Talas Region",
    "Issyk-Kul Region",
    "Osh City",
    "Laos",
    "Attapeu province",
    "Bokeo province",
    "Bolikhamxai province",
    "Champasak province",
    "Houaphanh province",
    "Khammouane province",
    "Luang Namtha province",
    "Luang Prabang province",
    "Oudomxay province",
    "Phongsaly province",
    "Salavan province",
    "Savannakhet province",
    "Vientiane province",
    "Vientiane Prefecture",
    "Sainyabuli province",
    "Sekong province",
    "Xaisomboun province",
    "Xiangkhouang province",
    "Latvia",
    "Ādaži",
    "Aizkraukle",
    "Alūksne",
    "Augšdaugava",
    "Balvi",
    "Bauska",
    "Cēsis",
    "Dobele",
    "Gulbene",
    "Jelgava",
    "Jēkabpils",
    "Ķekava",
    "Krāslava",
    "Kuldīga",
    "Limbaži",
    "Līvāni",
    "Ludza",
    "Madona",
    "Mārupe",
    "Ogre",
    "Olaine",
    "Preiļi",
    "Rēzekne",
    "Ropaži",
    "Salaspils",
    "Saldus",
    "Saulkrasti",
    "Sigulda",
    "Smiltene",
    "South Kurzeme",
    "Talsi",
    "Tukums",
    "Valka",
    "Valmiera",
    "Varakļāni",
    "Ventspils",
    "Lebanon",
    "Akkar",
    "Baalbek-Hermel",
    "Beirut",
    "Beqaa",
    "Keserwan-Jbeil",
    "Mount Lebanon",
    "Nabatieh",
    "Lesotho",
    "Berea",
    "Butha-Buthe",
    "Leribe",
    "Mafeteng",
    "Maseru",
    "Mohale's Hoek",
    "Mokhotlong",
    "Qacha's Nek",
    "Quthing",
    "Thaba-Tseka",
    "Liberia",
    "Bomi",
    "Bong",
    "Gbarpolu",
    "Grand Bassa",
    "Grand Cape Mount",
    "Grand Gedeh",
    "Grand Kru",
    "Lofa",
    "Margibi",
    "Maryland",
    "Montserrado",
    "Nimba",
    "Rivercess",
    "River Gee",
    "Sinoe",
    "Libya",
    "Al Butnan",
    "Darnah",
    "Al Jabal al Akhdar",
    "Al Marj",
    "Banghazi",
    "Al Wahat",
    "Al Kufrah",
    "Surt",
    "Misrata",
    "Marqab",
    "Tarabulus",
    "Al Jafarah",
    "Az Zawiyah",
    "An Nuqat al Khams",
    "Al Jabal al Gharbi",
    "Nalut",
    "Al Jufrah",
    "Wadi ash Shati'",
    "Sabha",
    "Wadi al Hayat",
    "Ghat",
    "Murzuq",
    "Liechtenstein",
    "Ruggell",
    "Schellenberg",
    "Gamprin",
    "Eschen",
    "Mauren",
    "Schaan",
    "Planken",
    "Vaduz",
    "Triesenberg",
    "Triesen",
    "Balzers",
    "Lithuania",
    "Alytus County",
    "Kaunas County",
    "Klaipėda County",
    "Marijampolė County",
    "Panevėžys County",
    "Šiauliai County",
    "Tauragė County",
    "Telšiai County",
    "Utena County",
    "Vilnius County",
    "Luxembourg",
    "Clervaux",
    "Wiltz",
    "Vianden",
    "Redange",
    "Diekirch",
    "Mersch",
    "Echternach",
    "Capellen",
    "Grevenmacher",
    "Esch-sur-Alzette",
    "Remich",
    "Macau",
    "Macau Peninsula",
    "Taipa",
    "Coloane",
    "Macedonia",
    "Region",
    "Northeastern",
    "Pelagonia",
    "Polog",
    "Skopje",
    "Southeastern",
    "Southwestern",
    "Vardar",
    "Madagascar",
    "Diana",
    "Sava",
    "Itasy",
    "Analamanga",
    "Vakinankaratra",
    "Bongolava",
    "Sofia",
    "Boeny",
    "Betsiboka",
    "Melaky",
    "Alaotra-Mangoro",
    "Atsinanana",
    "Analanjirofo",
    "Amoron'i Mania",
    "Matsiatra Ambony",
    "Fitovinany",
    "Vatovavy",
    "Atsimo-Atsinanana",
    "Ihorombe",
    "Menabe",
    "Atsimo-Andrefana",
    "Androy",
    "Anosy",
    "Malawi",
    "Malaysia",
    "Johor",
    "Kedah",
    "Kelantan",
    "Malacca",
    "Negeri Sembilan",
    "Pahang",
    "Penang",
    "Perak",
    "Perlis",
    "Sabah",
    "Sarawak",
    "Selangor",
    "Terengganu",
    "Maldives",
    "Haa Alif",
    "Shaviyani",
    "Noonu",
    "Raa",
    "Baa",
    "Lhaviyani",
    "Kaafu",
    "Alif Alif",
    "Alif Dhaal",
    "Vaavu",
    "Meemu",
    "Faafu",
    "Dhaalu",
    "Thaa",
    "Laamu",
    "Gaafu Alif",
    "Gaafu Dhaalu",
    "Mali",
    "Kayes",
    "Koulikoro",
    "Bamako",
    "Sikasso",
    "Ségou",
    "Mopti",
    "Tombouctou",
    "Gao",
    "Kidal",
    "Taoudénit",
    "Ménaka",
    "Malta",
    "Central Region",
    "Gozo Region",
    "Northern Region",
    "South Eastern Region",
    "Marshall Islands",
    "Ailinglaplap Atoll",
    "Ailuk Atoll",
    "Arno Atoll",
    "Aur Atoll",
    "Ebon Atoll",
    "Enewetok / Ujelang",
    "Jabat Island",
    "Jaluit Atoll",
    "Kili / Bikini / Ejit",
    "Kwajalein Atoll",
    "Lae Atoll",
    "Lib Island",
    "Likiep Atoll",
    "Majuro",
    "Maloelap Atoll",
    "Mejit Island",
    "Mili Atoll",
    "Namorik Atoll",
    "Namu Atoll",
    "Rongelap Atoll",
    "Ujae Atoll",
    "Utirik Atoll",
    "Wotho Atoll",
    "Martinique",
    "Le Marin",
    "Saint-Pierre",
    "La Trinité",
    "Mauritania",
    "Adrar",
    "Assaba",
    "Brakna",
    "Dakhlet Nouadhibou",
    "Gorgol",
    "Guidimaka",
    "Hodh Ech Chargui",
    "Hodh El Gharbi",
    "Inchiri",
    "Nouakchott-Nord",
    "Nouakchott-Ouest",
    "Nouakchott-Sud",
    "Tagant",
    "Tiris Zemmour",
    "Trarza",
    "Mauritius",
    "Flacq",
    "Grand Port",
    "Moka",
    "Pamplemousses",
    "Plaines Wilhems",
    "Port Louis",
    "Rivière du Rempart",
    "Rivière Noire",
    "Savanne",
    "Mayotte",
    "Petite Terre",
    "Grande Terre",
    "Mexico",
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila",
    "Colima",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "México",
    "Mexico City",
    "Michoacán",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas",
    "Moldova",
    "Bălți Municipality",
    "Briceni",
    "Dondușeni",
    "Drochia",
    "Edineț",
    "Fălești",
    "Florești",
    "Glodeni",
    "Ocnița",
    "Rîșcani",
    "Sîngerei",
    "Soroca",
    "Chișinău Municipality",
    "Anenii Noi",
    "Călărași",
    "Criuleni",
    "Dubăsari",
    "Hîncești",
    "Ialoveni",
    "Nisporeni",
    "Orhei",
    "Rezina",
    "Șoldănești",
    "Strășeni",
    "Tighina Municipality",
    "Telenești",
    "Ungheni",
    "Basarabeasca",
    "Cahul",
    "Cantemir",
    "Căușeni",
    "Cimișlia",
    "Leova",
    "Ștefan Vodă",
    "Taraclia",
    "Monaco",
    "Monaco-Ville",
    "Monte Carlo/Spélugues",
    "La Rousse/Saint Roman",
    "Larvotto/Bas Moulins",
    "Saint Michel",
    "La Condamine",
    "La Colle",
    "Les Révoires",
    "Moneghetti/Bd de Belgique",
    "Fontvieille",
    "Mongolia",
    "Arkhangai",
    "Bayankhongor",
    "Bayan-Ölgii",
    "Bulgan",
    "Darkhan-Uul",
    "Dornod",
    "Dornogovi",
    "Dundgobi",
    "Govi-Altai",
    "Govisümber",
    "Khentii",
    "Khovd",
    "Khövsgöl",
    "Orkhon",
    "Ömnögovi",
    "Övörkhangai",
    "Selenge",
    "Sükhbaatar",
    "Töv",
    "Uvs",
    "Zavkhan",
    "Ulaanbaatar",
    "Montenegro",
    "Andrijevica",
    "Bar",
    "Berane",
    "Bijelo Polje",
    "Budva",
    "Cetinje",
    "Danilovgrad",
    "Gusinje",
    "Herceg Novi",
    "Kolašin",
    "Kotor",
    "Mojkovac",
    "Nikšić",
    "Petnjica",
    "Plav",
    "Pljevlja",
    "Plužine",
    "Podgorica",
    "Rožaje",
    "Šavnik",
    "Tivat",
    "Tuzi",
    "Ulcinj",
    "Žabljak",
    "Zeta",
    "Montserrat",
    "Parish of Saint Peter",
    "Parish of Saint Georges",
    "Parish of Saint Anthony",
    "Morocco",
    "Tanger-Tétouan-Al Hoceïma",
    "L'Oriental",
    "Fès-Meknès",
    "Rabat-Salé-Kénitra",
    "Béni Mellal-Khénifra",
    "Casablanca-Settat",
    "Marrakech-Safi",
    "Drâa-Tafilalet",
    "Souss-Massa",
    "Guelmim-Oued Noun",
    "Laâyoune-Sakia El Hamra",
    "Dakhla-Oued Ed-Dahab",
    "Mozambique",
    "Cabo Delgado",
    "Gaza",
    "Inhambane",
    "Manica",
    "Maputo City",
    "Maputo",
    "Nampula",
    "Niassa",
    "Sofala",
    "Tete",
    "Zambezia",
    "Namibia",
    "Khomas",
    "Ohangwena",
    "Omusati",
    "Oshikoto",
    "Oshana",
    "Erongo",
    "Otjozondjupa",
    "Kavango East",
    "Zambezi",
    "Kunene",
    "Kavango West",
    "Hardap",
    "!Karas",
    "Omaheke",
    "Nauru",
    "Aiwo",
    "Anabar",
    "Anetan",
    "Boe",
    "Buada",
    "Meneng",
    "Ubenide",
    "Yaren",
    "Nepal",
    "Koshi",
    "Madhesh",
    "Bagmati",
    "Gandaki",
    "Lumbini",
    "Karnali",
    "Sudurpashchim",
    "Netherlands",
    "Drenthe",
    "Flevoland",
    "Friesland",
    "Gelderland",
    "Groningen",
    "North Brabant",
    "North Holland",
    "Overijssel",
    "South Holland",
    "Utrecht",
    "Zeeland",
    "Netherlands Antilles",
    "Curacao",
    "Bonaire",
    "Saba",
    "Sint Eustatius",
    "Sint Maarten",
    "New Caledonia",
    "Loyalty Islands Province",
    "North Province",
    "South Province",
    "New Zealand",
    "Auckland",
    "Bay of Plenty",
    "Canterbury",
    "Chatham Islands",
    "Gisborne",
    "Hawke's Bay",
    "Manawatu-Wanganui",
    "Marlborough",
    "Nelson",
    "Northland",
    "Otago",
    "Southland",
    "Taranaki",
    "Tasman",
    "Waikato",
    "Wellington",
    "West Coast",
    "Nicaragua",
    "Boaco",
    "Carazo",
    "Chinandega",
    "Chontales",
    "Estelí",
    "Granada",
    "Jinotega",
    "León",
    "Madriz",
    "Managua",
    "Masaya",
    "Matagalpa",
    "Nueva Segovia",
    "Rivas",
    "Río San Juan",
    "North Caribbean Coast Autonomous Region",
    "South Caribbean Coast Autonomous Region",
    "Niger",
    "Agadez",
    "Diffa",
    "Dosso",
    "Maradi",
    "Niamey*",
    "Tahoua",
    "Tillabéri",
    "Zinder",
    "Nigeria",
    "Abia",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
    "Niue",
    "Motu ",
    "Tafiti",
    "Norfolk Island",
    "Phillip Island",
    "Nepean Island",
    "North Korea",
    "Chagang",
    "North Hamgyong",
    "South Hamgyong",
    "North Hwanghae",
    "South Hwanghae",
    "Kangwon",
    "North Pyongan",
    "South Pyongan",
    "Ryanggang",
    "Northern Mariana Islands",
    "Farallon de Pajaros",
    "Maug Islands",
    "Supply reef",
    "Asuncion Island",
    "Agrihan",
    "Pagan",
    "Alamagan",
    "Guguan",
    "Zealandia Bank",
    "Sarigan",
    "Anatahan",
    "Farallon de Medinilla",
    "Saipan",
    "Mañagaha",
    "Bird Island",
    "Forbidden Island",
    "Tinian",
    "Aguijan",
    "Naftan Rock",
    "Rota",
    "Norway",
    "Oslo",
    "Rogaland",
    "Møre og Romsdal",
    "Nordland",
    "Østfold",
    "Akershus",
    "Buskerud",
    "Innlandet",
    "Vestfold",
    "Telemark",
    "Agder",
    "Vestland",
    "Trøndelag",
    "Troms",
    "Finnmark",
    "Oman",
    "Ad Dakhiliyah",
    "Ad Dhahirah",
    "Al Batinah North",
    "Al Batinah South",
    "Al Buraymi",
    "Al Wusta",
    "Ash Sharqiyah North",
    "Ash Sharqiyah South",
    "Dhofar",
    "Muscat",
    "Musandam",
    "Pakistan",
    "Azad Jammu and Kashmir",
    "Balochistan",
    "Gilgit-Baltistan",
    "Islamabad Capital Territory",
    "Khyber Pakhtunkhwa",
    "Sindh",
    "Palau",
    "Kayangel",
    "Aimeliik",
    "Airai",
    "Melekeok",
    "Ngaraard",
    "Ngarchelong",
    "Ngardmau",
    "Ngeremlengui",
    "Ngatpang",
    "Ngchesar",
    "Ngiwal",
    "Angaur",
    "Koror",
    "Peleliu",
    "Hatohobei",
    "Sonsorol",
    "Palestine",
    "Jenin",
    "Tubas",
    "Tulkarm",
    "Nablus",
    "Qalqilya",
    "Salfit",
    "Ramallah and al-Bireh",
    "Jericho",
    "Bethlehem",
    "Hebron",
    "North Gaza",
    "Deir al-Balah",
    "Khan Yunis",
    "Rafah",
    "Panama",
    "Bocas del Toro",
    "Chiriquí",
    "Coclé",
    "Darién",
    "Herrera",
    "Los Santos",
    "Panamá",
    "Panamá Oeste",
    "Veraguas",
    "Papua New Guinea",
    "Chimbu (Simbu)",
    "Eastern Highlands",
    "East New Britain",
    "East Sepik",
    "Enga",
    "Gulf",
    "Madang",
    "Manus",
    "Milne Bay",
    "Morobe",
    "New Ireland",
    "Oro (Northern)",
    "Bougainville",
    "Southern Highlands",
    "Western (Fly)",
    "Western Highlands",
    "West New Britain",
    "Sandaun (West Sepik)",
    "National Capital District",
    "Hela",
    "Jiwaka",
    "Paraguay",
    "Distrito Capital",
    "Concepción",
    "San Pedro",
    "Cordillera",
    "Guairá",
    "Caaguazú",
    "Caazapá",
    "Itapúa",
    "Paraguarí",
    "Alto Paraná",
    "Ñeembucú",
    "Amambay",
    "Canindeyú",
    "Presidente Hayes",
    "Alto Paraguay",
    "Boquerón",
    "Peru",
    "Ancash",
    "Apurímac",
    "Arequipa",
    "Ayacucho",
    "Cajamarca",
    "Cuzco",
    "Huancavelica",
    "Huánuco",
    "Ica",
    "Junín",
    "Lambayeque",
    "Lima",
    "Loreto",
    "Madre de Dios",
    "Moquegua",
    "Pasco",
    "Piura",
    "Puno",
    "San Martin",
    "Tacna",
    "Tumbes",
    "Ucayali",
    "Philippines",
    "National Capital Region",
    "Cordillera Administrative Region",
    "Ilocos Region",
    "Cagayan Valley",
    "Central Luzon",
    "Calabarzon",
    "Southwestern Tagalog Region",
    "Bicol Region",
    "Western Visayas",
    "Central Visayas",
    "Eastern Visayas",
    "Zamboanga Peninsula",
    "Northern Mindanao",
    "Davao Region",
    "Soccsksargen",
    "Caraga",
    "Bangsamoro",
    "Poland",
    "Lower Silesian",
    "Kuyavian-Pomeranian",
    "Lublin",
    "Lubusz",
    "Łódź",
    "Lesser Poland",
    "Masovian",
    "Opole",
    "Subcarpathian",
    "Podlaskie",
    "Pomeranian",
    "Silesian",
    "Holy Cross",
    "Warmian-Masurian",
    "Greater Poland",
    "West Pomeranian",
    "Portugal",
    "Azores",
    "Aveiro",
    "Beja",
    "Braga",
    "Bragança",
    "Castelo Branco",
    "Coimbra",
    "Évora",
    "Faro",
    "Guarda",
    "Leiria",
    "Lisbon",
    "Madeira",
    "Portalegre",
    "Porto",
    "Santarém",
    "Setúbal",
    "Viana do Castelo",
    "Vila Real",
    "Viseu",
    "Puerto Rico",
    "Adjuntas",
    "Aguada",
    "Aguadilla",
    "Aguas Buenas",
    "Aibonito",
    "Añasco",
    "Arecibo",
    "Arroyo",
    "Barceloneta",
    "Barranquitas",
    "Bayamón",
    "Cabo Rojo",
    "Caguas",
    "Camuy",
    "Canóvanas",
    "Carolina",
    "Cataño",
    "Cayey",
    "Ceiba",
    "Ciales",
    "Cidra",
    "Coamo",
    "Comerío",
    "Culebra",
    "Dorado",
    "Fajardo",
    "Florida",
    "Guánica",
    "Guayama",
    "Guayanilla",
    "Guaynabo",
    "Gurabo",
    "Hatillo",
    "Hormigueros",
    "Humacao",
    "Isabela",
    "Jayuya",
    "Juana Díaz",
    "Juncos",
    "Lajas",
    "Lares",
    "Las Marías",
    "Las Piedras",
    "Loíza",
    "Luquillo",
    "Manatí",
    "Maricao",
    "Maunabo",
    "Mayagüez",
    "Moca",
    "Morovis",
    "Naguabo",
    "Naranjito",
    "Orocovis",
    "Patillas",
    "Peñuelas",
    "Ponce",
    "Quebradillas",
    "Rincón",
    "Río Grande",
    "Sabana Grande",
    "Salinas",
    "San Germán",
    "San Lorenzo",
    "San Sebastián",
    "Santa Isabel",
    "Toa Alta",
    "Toa Baja",
    "Trujillo Alto",
    "Utuado",
    "Vega Alta",
    "Vega Baja",
    "Vieques",
    "Villalba",
    "Yabucoa",
    "Yauco",
    "Qatar",
    "Al Shamal",
    "Al Khor",
    "Al-Shahaniya",
    "Umm Salal",
    "Al Daayen",
    "Ad Dawhah (Doha)",
    "Al Rayyan",
    "Al Wakrah",
    "Republic of the Congo",
    "Kouilou",
    "Niari",
    "Lékoumou",
    "Bouenza",
    "Pool",
    "Plateaux",
    "Cuvette",
    "Cuvette-Ouest",
    "Sangha",
    "Likouala",
    "Brazzaville",
    "Pointe-Noire",
    "Réunion",
    "Saint-Benoît",
    "Saint-Denis",
    "Saint-Paul",
    "Romania",
    "Alba",
    "Arad",
    "Argeș",
    "Bacău",
    "Bihor",
    "Bistrița-Năsăud",
    "Botoșani",
    "Brașov",
    "Brăila",
    "Bucharest",
    "Buzău",
    "Caraș-Severin",
    "Cluj",
    "Constanța",
    "Covasna",
    "Dâmbovița",
    "Dolj",
    "Galați",
    "Giurgiu",
    "Gorj",
    "Harghita",
    "Hunedoara",
    "Ialomița",
    "Iași",
    "Ilfov",
    "Maramureș",
    "Mehedinți",
    "Mureș",
    "Neamț",
    "Olt",
    "Prahova",
    "Satu Mare",
    "Sălaj",
    "Sibiu",
    "Suceava",
    "Teleorman",
    "Timiș",
    "Tulcea",
    "Vaslui",
    "Vâlcea",
    "Vrancea",
    "Russia",
    "Adygea",
    "Bashkortostan",
    "Buryatia",
    "Altai Republic",
    "Dagestan",
    "Ingushetia",
    "Kabardino-Balkaria",
    "Kalmykia",
    "Karachay-Cherkessia",
    "Karelia",
    "Komi Republic",
    "Mari El",
    "Mordovia",
    "Sakha (Yakutia)",
    "North Ossetia–Alania",
    "Tatarstan",
    "Tuva",
    "Udmurtia",
    "Khakassia",
    "Chechnya",
    "Chuvashia",
    "Altai Krai",
    "Krasnodar Krai",
    "Krasnoyarsk Krai",
    "Primorsky Krai",
    "Stavropol Krai",
    "Khabarovsk Krai",
    "Amur Oblast",
    "Arkhangelsk Oblast",
    "Astrakhan Oblast",
    "Belgorod Oblast",
    "Bryansk Oblast",
    "Vladimir Oblast",
    "Volgograd Oblast",
    "Vologda Oblast",
    "Voronezh Oblast",
    "Ivanovo Oblast",
    "Irkutsk Oblast",
    "Kaliningrad Oblast",
    "Kaluga Oblast",
    "Kamchatka Krai",
    "Kemerovo Oblast",
    "Kirov Oblast",
    "Kostroma Oblast",
    "Kurgan Oblast",
    "Kursk Oblast",
    "Leningrad Oblast",
    "Lipetsk Oblast",
    "Magadan Oblast",
    "Moscow Oblast",
    "Murmansk Oblast",
    "Nizhny Novgorod Oblast",
    "Novgorod Oblast",
    "Novosibirsk Oblast",
    "Omsk Oblast",
    "Orenburg Oblast",
    "Oryol Oblast",
    "Penza Oblast",
    "Perm Krai",
    "Pskov Oblast",
    "Rostov Oblast",
    "Ryazan Oblast",
    "Samara Oblast",
    "Saratov Oblast",
    "Sakhalin Oblast",
    "Sverdlovsk Oblast",
    "Smolensk Oblast",
    "Tambov Oblast",
    "Tver Oblast",
    "Tomsk Oblast",
    "Tula Oblast",
    "Tyumen Oblast",
    "Ulyanovsk Oblast",
    "Chelyabinsk Oblast",
    "Zabaykalsky Krai",
    "Yaroslavl Oblast",
    "Moscow",
    "Saint Petersburg",
    "Jewish Autonomous Oblast",
    "Nenets Autonomous Okrug",
    "Khanty–Mansi Autonomous Okrug – Yugra",
    "Chukotka Autonomous Okrug",
    "Yamalo-Nenets Autonomous Okrug",
    "Republic of Crimea",
    "Sevastopol",
    "Donetsk People's Republic",
    "Luhansk People's Republic",
    "Zaporizhzhia Oblast",
    "Kherson Oblast",
    "Rwanda",
    "Kigali",
    "Saint Barthélemy",
    "Colombier",
    "Flamands",
    "Terre Neuve",
    "Grande Vigie",
    "Corossol",
    "Merlette",
    "La Grande Montagne",
    "Anse des Lézards",
    "Anse des Cayes",
    "Le Palidor",
    "Public",
    "Col de la Tourmente",
    "Quartier du Roi",
    "Le Château",
    "Aéroport",
    "Saint-Jean",
    "Gustavia",
    "La Pointe",
    "Lurin",
    "Carénage",
    "Morne Criquet",
    "Morne de Dépoudré",
    "Gouverneur",
    "Anse du Gouverneur",
    "Morne Rouge",
    "Grande Saline",
    "Petite Saline",
    "Lorient",
    "Barrière des Quatres Vents",
    "Camaruche",
    "Grand Fond",
    "Toiny",
    "Devet",
    "Vitet",
    "Grand Cul-de-Sac",
    "Pointe Milou",
    "Mont Jean",
    "Marigot",
    "Anse du Grand Cul-de-Sac",
    "Petit Cul-de-Sac",
    "Saint Helena",
    "Alarm Forest",
    "Blue Hill",
    "Half Tree Hollow",
    "Jamestown",
    "Levelwood",
    "Longwood",
    "Sandy Bay",
    "Saint Paul's",
    "Saint Kitts and Nevis",
    "Saint Thomas Lowland",
    "Saint John Figtree",
    "Saint George Gingerland",
    "Saint Paul Charlestown",
    "Saint James Windward",
    "Saint George Basseterre",
    "Trinity Palmetto Point",
    "Saint Thomas Middle Island",
    "Saint Anne Sandy Point",
    "Saint Paul Capesterre",
    "Saint John Capesterre",
    "Christ Church Nichola Town,Saint Kitts",
    "Saint Mary Cayon",
    "Saint Peter Basseterre",
    "Saint Martin",
    "Collectivity of Saint Martin",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Charlotte Parish",
    "Grenadines Parish",
    "Saint Andrew Parish",
    "Saint David Parish",
    "Saint George Parish",
    "Saint Patrick Parish",
    "Samoa",
    "Tuamasaga",
    "A'ana",
    "Aiga-i-le-Tai",
    "Atua",
    "Va'a-o-Fonoti",
    "Fa'asaleleaga",
    "Gaga'emauga",
    "Gaga'ifomauga",
    "Vaisigano",
    "Satupa'itea",
    "Palauli",
    "San Marino",
    "Acquaviva",
    "Borgo Maggiore",
    "Chiesanuova",
    "City of San Marino",
    "Domagnano",
    "Faetano",
    "Fiorentino",
    "Montegiardino",
    "Serravalle",
    "São Tomé and Príncipe",
    "Água Grande",
    "Cantagalo",
    "Caué",
    "Lembá",
    "Lobata",
    "Mé-Zóchi",
    "Autonomous Region of Príncipe",
    "Saudi Arabia",
    "Riyadh Province",
    "Mecca Province",
    "Eastern Province",
    "Medina Province",
    "Asir Province",
    "Jazan Province",
    "Al-Qassim Province",
    "Tabuk Province",
    "Ḥa'il Province",
    "Al-Jawf Province",
    "Najran Province",
    "Northern Borders Province",
    "Al-Bahah Province",
    "Senegal",
    "Dakar",
    "Diourbel",
    "Fatick",
    "Kaffrine",
    "Kaolack",
    "Kédougou",
    "Kolda",
    "Louga",
    "Matam",
    "Saint-Louis",
    "Sédhiou",
    "Tambacounda",
    "Thiès",
    "Ziguinchor",
    "Serbia",
    "Kolubara District",
    "Mačva District",
    "Moravica District",
    "Pomoravlje District",
    "Rasina District",
    "Raška District",
    "Šumadija District",
    "Zlatibor District",
    "Bor District",
    "Braničevo District",
    "Jablanica District",
    "Nišava District",
    "Pčinja District",
    "Pirot District",
    "Podunavlje District",
    "Toplica District",
    "Zaječar District",
    "Central Banat District",
    "North Bačka District",
    "North Banat District",
    "South Bačka District",
    "South Banat District",
    "Srem District",
    "West Bačka District",
    "Kosovo District",
    "Kosovo-Pomoravlje District",
    "Kosovska Mitrovica District",
    "Peć District",
    "Prizren District",
    "Seychelles",
    "Mahe Islands",
    "Anse aux Pins",
    "Anse Boileau",
    "Anse Etoile",
    "Au Cap",
    "Anse Royale",
    "Baie Lazare",
    "Beau Vallon",
    "Bel Air",
    "Bel Ombre",
    "Cascade",
    "Glacis",
    "English River",
    "Mont Buxton",
    "Mont Fleuri",
    "Plaisance",
    "Pointe La Rue",
    "Port Glaud",
    "Saint Louis",
    "Takamaka",
    "Les Mamelles",
    "Roche Caïman",
    "Praslin Islands",
    "Baie Sainte Anne",
    "Grand'Anse Praslin",
    "La Digue Islands",
    "La Digue and Inner Islands",
    "Outer Islands",
    "Sierra Leone",
    "Kailahun",
    "Kenema",
    "Kono",
    "Bombali",
    "Falaba",
    "Koinadugu",
    "Tonkolili",
    "Kambia",
    "Karene",
    "Port Loko",
    "Bo",
    "Bonthe",
    "Moyamba",
    "Pujehun",
    "Western Rural",
    "Western Urban",
    "Singapore",
    "Ang Mo Kio GRC",
    "Bishan–Toa Payoh GRC",
    "Jalan Besar GRC",
    "Tanjong Pagar GRC",
    "Potong Pasir SMC",
    "Radin Mas SMC",
    "Marymount SMC",
    "Kebun Baru SMC",
    "Yio Chu Kang SMC",
    "Aljunied GRC",
    "Sengkang GRC",
    "Pasir Ris–Punggol GRC",
    "Tampines GRC",
    "Hougang SMC",
    "Punggol West SMC",
    "Holland–Bukit Timah GRC",
    "Marsiling–Yew Tee GRC",
    "Nee Soon GRC",
    "Sembawang GRC",
    "Bukit Panjang SMC",
    "East Coast GRC",
    "Marine Parade GRC",
    "MacPherson SMC",
    "Mountbatten SMC",
    "Chua Chu Kang GRC",
    "Jurong GRC",
    "West Coast GRC",
    "Bukit Batok SMC",
    "Hong Kah North SMC",
    "Pioneer SMC",
    "Yuhua SMC",
    "Slovakia",
    "Bratislava",
    "Trnava",
    "Trenčín",
    "Nitra",
    "Žilina",
    "Banská Bystrica",
    "Prešov",
    "Košice",
    "Slovenia",
    "Municipality of Ajdovščina",
    "Municipality of Ankaran",
    "Municipality of Apače",
    "Municipality of Beltinci",
    "Municipality of Benedikt",
    "Municipality of Bistrica ob Sotli",
    "Municipality of Bled",
    "Municipality of Bloke",
    "Municipality of Bohinj",
    "Municipality of Borovnica",
    "Municipality of Bovec",
    "Municipality of Braslovče",
    "Municipality of Brda",
    "Municipality of Brezovica",
    "Municipality of Brežice",
    "Municipality of Cankova",
    "Urban Municipality of Celje",
    "Municipality of Cerklje na Gorenjskem",
    "Municipality of Cerknica",
    "Municipality of Cerkno",
    "Municipality of Cerkvenjak",
    "Municipality of Cirkulane",
    "Municipality of Črenšovci",
    "Municipality of Črna na Koroškem",
    "Municipality of Črnomelj",
    "Municipality of Destrnik",
    "Municipality of Divača",
    "Municipality of Dobje",
    "Municipality of Dobrepolje",
    "Municipality of Dobrna",
    "Municipality of Dobrova–Polhov Gradec",
    "Municipality of Dobrovnik",
    "Municipality of Dol pri Ljubljani",
    "Municipality of Dolenjske Toplice",
    "Municipality of Domžale",
    "Municipality of Dornava",
    "Municipality of Dravograd",
    "Municipality of Duplek",
    "Municipality of Gorenja Vas–Poljane",
    "Municipality of Gorišnica",
    "Municipality of Gorje",
    "Municipality of Gornja Radgona",
    "Municipality of Gornji Grad",
    "Municipality of Gornji Petrovci",
    "Municipality of Grad",
    "Municipality of Grosuplje",
    "Municipality of Hajdina",
    "Municipality of Hoče-Slivnica",
    "Municipality of Hodoš",
    "Municipality of Horjul",
    "Municipality of Hrastnik",
    "Municipality of Hrpelje-Kozina",
    "Municipality of Idrija",
    "Municipality of Ig",
    "Municipality of Ilirska Bistrica",
    "Municipality of Ivančna Gorica",
    "Municipality of Izola",
    "Municipality of Jesenice",
    "Municipality of Jezersko",
    "Municipality of Juršinci",
    "Municipality of Kamnik",
    "Municipality of Kanal ob Soči",
    "Municipality of Kidričevo",
    "Municipality of Kobarid",
    "Municipality of Kobilje",
    "Municipality of Kočevje",
    "Municipality of Komen",
    "Municipality of Komenda",
    "Urban Municipality of Koper",
    "Municipality of Kostanjevica na Krki",
    "Municipality of Kostel",
    "Municipality of Kozje",
    "Urban Municipality of Kranj",
    "Municipality of Kranjska Gora",
    "Municipality of Križevci",
    "Urban Municipality of Krško",
    "Municipality of Kungota",
    "Municipality of Kuzma",
    "Municipality of Laško",
    "Municipality of Lenart",
    "Municipality of Lendava",
    "Municipality of Litija",
    "Urban Municipality of Ljubljana",
    "Municipality of Ljubno",
    "Municipality of Ljutomer",
    "Municipality of Log-Dragomer",
    "Municipality of Logatec",
    "Municipality of Loška Dolina",
    "Municipality of Loški Potok",
    "Municipality of Lovrenc na Pohorju",
    "Municipality of Luče",
    "Municipality of Lukovica",
    "Municipality of Majšperk",
    "Municipality of Makole",
    "Urban Municipality of Maribor",
    "Municipality of Markovci",
    "Municipality of Medvode",
    "Municipality of Mengeš",
    "Municipality of Metlika",
    "Municipality of Mežica",
    "Municipality of Miklavž na Dravskem Polju",
    "Municipality of Miren-Kostanjevica",
    "Municipality of Mirna",
    "Municipality of Mirna Peč",
    "Municipality of Mislinja",
    "Municipality of Mokronog-Trebelno",
    "Municipality of Moravče",
    "Municipality of Moravske Toplice",
    "Municipality of Mozirje",
    "Urban Municipality of Murska Sobota",
    "Municipality of Muta",
    "Municipality of Naklo",
    "Municipality of Nazarje",
    "Urban Municipality of Nova Gorica",
    "Urban Municipality of Novo Mesto",
    "Municipality of Odranci",
    "Municipality of Oplotnica",
    "Municipality of Ormož",
    "Municipality of Osilnica",
    "Municipality of Pesnica",
    "Municipality of Piran",
    "Municipality of Pivka",
    "Municipality of Podčetrtek",
    "Municipality of Podlehnik",
    "Municipality of Podvelka",
    "Municipality of Poljčane",
    "Municipality of Polzela",
    "Municipality of Postojna",
    "Municipality of Prebold",
    "Municipality of Preddvor",
    "Municipality of Prevalje",
    "Urban Municipality of Ptuj",
    "Municipality of Puconci",
    "Municipality of Rače-Fram",
    "Municipality of Radeče",
    "Municipality of Radenci",
    "Municipality of Radlje ob Dravi",
    "Municipality of Radovljica",
    "Municipality of Ravne na Koroškem",
    "Municipality of Razkrižje",
    "Municipality of Rečica ob Savinji",
    "Municipality of Renče–Vogrsko",
    "Municipality of Ribnica",
    "Municipality of Ribnica na Pohorju",
    "Municipality of Rogaška Slatina",
    "Municipality of Rogašovci",
    "Municipality of Rogatec",
    "Municipality of Ruše",
    "Municipality of Šalovci",
    "Municipality of Selnica ob Dravi",
    "Municipality of Semič",
    "Municipality of Šempeter-Vrtojba",
    "Municipality of Šenčur",
    "Municipality of Šentilj",
    "Municipality of Šentjernej",
    "Municipality of Šentjur",
    "Municipality of Šentrupert",
    "Municipality of Sevnica",
    "Municipality of Sežana",
    "Municipality of Škocjan",
    "Municipality of Škofja Loka",
    "Municipality of Škofljica",
    "Urban Municipality of Slovenj Gradec",
    "Municipality of Slovenska Bistrica",
    "Municipality of Slovenske Konjice",
    "Municipality of Šmarje pri Jelšah",
    "Municipality of Šmarješke Toplice",
    "Municipality of Šmartno ob Paki",
    "Municipality of Šmartno pri Litiji",
    "Municipality of Sodražica",
    "Municipality of Solčava",
    "Municipality of Šoštanj",
    "Municipality of Središče ob Dravi",
    "Municipality of Starše",
    "Municipality of Štore",
    "Municipality of Straža",
    "Municipality of Sveta Ana",
    "Municipality of Sveta Trojica v Slovenskih Goricah",
    "Municipality of Sveti Andraž v Slovenskih Goricah",
    "Municipality of Sveti Jurij ob Ščavnici",
    "Municipality of Sveti Jurij v Slovenskih Goricah",
    "Municipality of Sveti Tomaž",
    "Municipality of Tabor",
    "Municipality of Tišina",
    "Municipality of Tolmin",
    "Municipality of Trbovlje",
    "Municipality of Trebnje",
    "Municipality of Trnovska Vas",
    "Municipality of Trzin",
    "Municipality of Tržič",
    "Municipality of Turnišče",
    "Urban Municipality of Velenje",
    "Municipality of Velika Polana",
    "Municipality of Velike Lašče",
    "Municipality of Veržej",
    "Municipality of Videm",
    "Municipality of Vipava",
    "Municipality of Vitanje",
    "Municipality of Vodice",
    "Municipality of Vojnik",
    "Municipality of Vransko",
    "Municipality of Vrhnika",
    "Municipality of Vuzenica",
    "Municipality of Zagorje ob Savi",
    "Municipality of Žalec",
    "Municipality of Zavrč",
    "Municipality of Železniki",
    "Municipality of Žetale",
    "Municipality of Žiri",
    "Municipality of Žirovnica",
    "Municipality of Zreče",
    "Municipality of Žužemberk",
    "Solomon Islands",
    "Central Province",
    "Choiseul Province",
    "Guadalcanal Province[1]",
    "Isabel Province",
    "Makira-Ulawa Province",
    "Malaita Province",
    "Rennell and Bellona Province",
    "Temotu Province",
    "Western Province",
    "Capital Territory",
    "Somalia",
    "Galmudug",
    "Hirshabelle",
    "Jubaland",
    "Puntland",
    "South West",
    "Somaliland",
    "South Africa",
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "North West",
    "Northern Cape",
    "Western Cape",
    "South Korea",
    "North Chungcheong",
    "South Chungcheong",
    "Gangwon",
    "Gyeonggi",
    "North Gyeongsang",
    "South Gyeongsang",
    "Jeonbuk",
    "South Jeolla",
    "Jeju",
    "Spain",
    "Andalusia",
    "Aragon",
    "Asturias",
    "Balearic Islands",
    "Basque Country",
    "Canary Islands",
    "Cantabria",
    "Castile and León",
    "Castilla–La Mancha",
    "Catalonia",
    "Extremadura",
    "Galicia",
    "Madrid",
    "Murcia",
    "Navarre",
    "Valencia",
    "Sri Lanka",
    "North Central",
    "North Western",
    "Sabaragamuwa",
    "Uva",
    "St. Lucia",
    "Anse la Raye",
    "Canaries",
    "Castries",
    "Choiseul",
    "Dennery",
    "Gros Islet",
    "Laborie",
    "Micoud",
    "Soufrière",
    "Vieux Fort",
    "Sudan",
    "Northern Bahr el Ghazal",
    "Western Bahr el Ghazal",
    "Lakes",
    "Warrap",
    "Western Equatoria",
    "Central Equatoria",
    "Eastern Equatoria",
    "Jonglei",
    "Unity",
    "Upper Nile",
    "Abyei Area",
    "Greater Pibor Area",
    "Ruweng Area",
    "Suriname",
    "Brokopondo",
    "Commewijne",
    "Coronie",
    "Marowijne",
    "Nickerie",
    "Para",
    "Paramaribo",
    "Saramacca",
    "Sipaliwini",
    "Wanica",
    "Swaziland",
    "Hhohho",
    "Manzini",
    "Lubombo",
    "Shiselweni",
    "Sweden",
    "Stockholm",
    "Uppsala",
    "Södermanland",
    "Östergötland",
    "Jönköping",
    "Kronoberg",
    "Kalmar",
    "Gotland",
    "Blekinge",
    "Skåne",
    "Halland",
    "Västra Götaland",
    "Värmland",
    "Örebro",
    "Västmanland",
    "Dalarna",
    "Gävleborg",
    "Västernorrland",
    "Jämtland",
    "Västerbotten",
    "Norrbotten",
    "Switzerland",
    "Zurich",
    "Bern",
    "Lucerne",
    "Uri",
    "Schwyz",
    "Obwald",
    "Nidwald",
    "Glarus",
    "Zoug / Zug",
    "Freiburg",
    "Solothurn",
    "Basel-City",
    "Basel-Country",
    "Schaffhouse",
    "Appenzell Outer-Rhodes",
    "Appenzell Inner-Rhodes",
    "St. Gall",
    "Grisons",
    "Argovia",
    "Thurgovia",
    "Ticino",
    "Vaud",
    "Wallis",
    "Neuchâtel",
    "Geneva",
    "Jura",
    "Syria",
    "Aleppo",
    "Raqqa",
    "As-Suwayda",
    "Damascus",
    "Daraa",
    "Deir ez-Zor",
    "Hama",
    "Al-Hasakah",
    "Homs",
    "Idlib",
    "Latakia",
    "Quneitra",
    "Rif Dimashq",
    "Tartus",
    "Taipei",
    "Taoyuan",
    "Kaohsiung",
    "New Taipei",
    "Taichung",
    "Tainan",
    "Tajikistan",
    "Sughd Region",
    "Districts under Republic Subordination",
    "Khatlon Region",
    "Gorno-Badakhshan Autonomous Region1",
    "Dushanbe",
    "Tanzania",
    "Arusha Region",
    "Dar es Salaam Region",
    "Dodoma Region",
    "Geita Region",
    "Iringa Region",
    "Kagera Region",
    "Katavi Region",
    "Kigoma Region",
    "Kilimanjaro Region",
    "Lindi Region",
    "Manyara Region",
    "Mara Region",
    "Mbeya Region",
    "Mjini Magharibi Region",
    "Morogoro Region",
    "Mtwara Region",
    "Mwanza Region",
    "Njombe Region",
    "Pemba North Region",
    "Pemba South Region",
    "Pwani Region",
    "Rukwa Region",
    "Ruvuma Region",
    "Shinyanga Region",
    "Simiyu Region",
    "Singida Region",
    "Songwe Region",
    "Tabora Region",
    "Tanga Region",
    "Unguja North Region",
    "Unguja South Region",
    "Thailand",
    "Bangkok",
    "Amnat Charoen",
    "Ang Thong",
    "Bueng Kan",
    "Buriram",
    "Chachoengsao",
    "Chai Nat",
    "Chaiyaphum",
    "Chanthaburi",
    "Chiang Mai",
    "Chiang Rai",
    "Chonburi",
    "Chumphon",
    "Kalasin",
    "Kamphaeng Phet",
    "Kanchanaburi",
    "Khon Kaen",
    "Krabi",
    "Lampang",
    "Lamphun",
    "Loei",
    "Lopburi",
    "Mae Hong Son",
    "Maha Sarakham",
    "Mukdahan",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nakhon Sawan",
    "Nakhon Si Thammarat",
    "Nan",
    "Narathiwat",
    "Nong Bua Lamphu",
    "Nong Khai",
    "Nonthaburi",
    "Pathum Thani",
    "Pattani",
    "Phang Nga",
    "Phatthalung",
    "Phayao",
    "Phetchabun",
    "Phetchaburi",
    "Phichit",
    "Phitsanulok",
    "Phra Nakhon Si Ayutthaya",
    "Phrae",
    "Phuket",
    "Prachinburi",
    "Prachuap Khiri Khan",
    "Ranong",
    "Ratchaburi",
    "Rayong",
    "Roi Et",
    "Sa Kaeo",
    "Sakon Nakhon",
    "Samut Prakan",
    "Samut Sakhon",
    "Samut Songkhram",
    "Saraburi",
    "Satun",
    "Sing Buri",
    "Sisaket",
    "Songkhla",
    "Sukhothai",
    "Suphan Buri",
    "Surat Thani",
    "Surin",
    "Tak",
    "Trang",
    "Trat",
    "Ubon Ratchathani",
    "Udon Thani",
    "Uthai Thani",
    "Uttaradit",
    "Yala",
    "Yasothon",
    "The Bahamas",
    "Acklins",
    "Berry Islands",
    "Bimini",
    "Cat Island",
    "Central Grand Bahama",
    "Crooked Island",
    "East Grand Bahama",
    "Exuma + Black Point",
    "Harbour Island",
    "Inagua",
    "Long Island",
    "Marco City",
    "Mayaguana",
    "The Gambia",
    "Banjul",
    "Central River",
    "Lower River",
    "North Bank",
    "Upper River",
    "Timor-Leste",
    "Lautém",
    "Baucau",
    "Viqueque",
    "Manatuto",
    "Dili",
    "Aileu",
    "Manufahi",
    "Liquiçá",
    "Ermera",
    "Ainaro",
    "Bobonaro",
    "Covalima",
    "Oecusse (SAR)",
    "Atauro",
    "Togo",
    "Centrale",
    "Kara",
    "Maritime",
    "Tokelau",
    "Atafu",
    "Nukunonu",
    "Fakaofo",
    "Tonga",
    "Tongatapu",
    "Vavaʻu",
    "Haʻapai",
    "ʻEua",
    "Ongo Niua",
    "Trinidad and Tobago",
    "Couva",
    "Tabaquite–Talparo",
    "Mayaro",
    "Rio Claro",
    "Tunapuna",
    "Piarco",
    "Laventille",
    "Bagatelle",
    "Belle Garden",
    "Bethel",
    "Bethesda",
    "Bon Accord",
    "Buccoo",
    "Darrel Spring",
    "Lambeau",
    "Mason Hall",
    "Mt. St. George",
    "Parlatuvier",
    "Plymouth",
    "Roxborough",
    "Scarborough",
    "Signal Hill",
    "Tunisia",
    "Ariana",
    "Béja",
    "Ben Arous",
    "Bizerte",
    "Gabès",
    "Gafsa",
    "Jendouba",
    "Kairouan",
    "Kasserine",
    "Kebili",
    "Kef",
    "Mahdia",
    "Manouba",
    "Medenine",
    "Monastir",
    "Nabeul",
    "Sfax",
    "Sidi Bouzid",
    "Siliana",
    "Sousse",
    "Tataouine",
    "Tozeur",
    "Tunis",
    "Zaghouan",
    "Turkey",
    "Adana",
    "Adıyaman",
    "Afyonkarahisar",
    "Ağrı",
    "Amasya",
    "Ankara",
    "Antalya",
    "Artvin",
    "Aydın",
    "Balıkesir",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Diyarbakır",
    "Edirne",
    "Elazığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkâri",
    "Hatay",
    "Isparta",
    "Mersin",
    "Istanbul",
    "İzmir",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kırklareli",
    "Kırşehir",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Malatya",
    "Manisa",
    "Kahramanmaraş",
    "Mardin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Rize",
    "Sakarya",
    "Samsun",
    "Siirt",
    "Sinop",
    "Sivas",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Şanlıurfa",
    "Uşak",
    "Van",
    "Yozgat",
    "Zonguldak",
    "Aksaray",
    "Bayburt",
    "Karaman",
    "Kırıkkale",
    "Batman",
    "Şırnak",
    "Bartın",
    "Ardahan",
    "Iğdır",
    "Yalova",
    "Karabük",
    "Kilis",
    "Osmaniye",
    "Düzce",
    "Turkmenistan",
    "Ashgabat",
    "Ahal Region",
    "Balkan Region",
    "Daşoguz Region",
    "Lebap Region",
    "Mary Region",
    "Turks and Caicos Islands",
    "Providenciales",
    "North Caicos",
    "Middle Caicos",
    "South Caicos",
    "Grand Turk",
    "Salt Cay",
    "Tuvalu",
    "Funafuti",
    "Nanumea",
    "Nui",
    "Nukufetau",
    "Nukulaelae",
    "Vaitupu",
    "Nanumanga",
    "Niulakita",
    "Niutao",
    "Uganda",
    "Buikwe",
    "Bukomansimbi",
    "Butambala",
    "Buvuma",
    "Gomba",
    "Kalangala",
    "Kalungu",
    "Kampala",
    "Kasanda",
    "Kayunga",
    "Kiboga",
    "Kyankwanzi",
    "Kyotera",
    "Luweero",
    "Lwengo",
    "Lyantonde",
    "Masaka",
    "Mityana",
    "Mpigi",
    "Mubende",
    "Mukono",
    "Nakaseke",
    "Nakasongola",
    "Rakai",
    "Sembabule",
    "Wakiso",
    "Amuria",
    "Budaka",
    "Bududa",
    "Bugiri",
    "Bugweri",
    "Bukedea",
    "Bukwo",
    "Bulambuli",
    "Butaleja",
    "Butebo",
    "Buyende",
    "Iganga",
    "Jinja",
    "Kaberamaido",
    "Kalaki",
    "Kaliro",
    "Kamuli",
    "Kapchorwa",
    "Kapelebyong",
    "Katakwi",
    "Kibuku",
    "Kumi",
    "Kween",
    "Luuka",
    "Manafwa",
    "Mayuge",
    "Mbale",
    "Namayingo",
    "Namisindwa",
    "Namutumba",
    "Ngora",
    "Pallisa",
    "Serere",
    "Sironko",
    "Soroti",
    "Tororo",
    "Abim",
    "Adjumani",
    "Agago",
    "Alebtong",
    "Amolatar",
    "Amudat",
    "Amuru",
    "Apac",
    "Arua",
    "Dokolo",
    "Gulu",
    "Kaabong",
    "Karenga",
    "Kitgum",
    "Koboko",
    "Kole",
    "Kotido",
    "Kwania",
    "Lamwo",
    "Lira",
    "Madi-Okollo",
    "Maracha",
    "Moroto",
    "Moyo",
    "Nabilatuk",
    "Nakapiripirit",
    "Napak",
    "Nebbi",
    "Nwoya",
    "Obongi",
    "Omoro",
    "Otuke",
    "Oyam",
    "Pader",
    "Pakwach",
    "Terego",
    "Yumbe",
    "Zombo",
    "Buhweju",
    "Buliisa",
    "Bundibugyo",
    "Bunyangabu",
    "Bushenyi",
    "Hoima",
    "Ibanda",
    "Isingiro",
    "Kabale",
    "Kabarole",
    "Kagadi",
    "Kakumiro",
    "Kamwenge",
    "Kanungu",
    "Kasese",
    "Kazo",
    "Kibaale",
    "Kikuube",
    "Kiruhura",
    "Kiryandongo",
    "Kisoro",
    "Kitagwenda",
    "Kyegegwa",
    "Kyenjojo",
    "Masindi",
    "Mbarara",
    "Mitooma",
    "Ntoroko",
    "Ntungamo",
    "Rubanda",
    "Rubirizi",
    "Rukiga",
    "Rukungiri",
    "Rwampara",
    "Sheema",
    "Ukraine",
    "Autonomous Republic of Crimea",
    "Vinnytsia Oblast",
    "Volyn Oblast",
    "Dnipropetrovsk Oblast",
    "Donetsk Oblast",
    "Zhytomyr Oblast",
    "Zakarpattia Oblast",
    "Ivano-Frankivsk Oblast",
    "Kyiv Oblast",
    "Kirovohrad Oblast",
    "Luhansk Oblast",
    "Lviv Oblast",
    "Mykolaiv Oblast",
    "Odesa Oblast",
    "Poltava Oblast",
    "Rivne Oblast",
    "Sumy Oblast",
    "Ternopil Oblast",
    "Kharkiv Oblast",
    "Khmelnytskyi Oblast",
    "Cherkasy Oblast",
    "Chernivtsi Oblast",
    "Chernihiv Oblast",
    "Kyiv",
    "United Arab Emirates",
    "United Kingdom",
    "Aberconwy and Colwyn",
    "Aberdeen City",
    "Aberdeenshire",
    "Anglesey",
    "Angus",
    "Antrim",
    "Argyll and Bute",
    "Armagh",
    "Avon",
    "Ayrshire",
    "Bath and NE Somerset",
    "Bedfordshire",
    "Belfast",
    "Berkshire",
    "Berwickshire",
    "BFPO",
    "Blaenau Gwent",
    "Buckinghamshire",
    "Caernarfonshire",
    "Caerphilly",
    "Caithness",
    "Cambridgeshire",
    "Cardiff",
    "Cardiganshire",
    "Carmarthenshire",
    "Ceredigion",
    "Channel Islands",
    "Cheshire",
    "City of Bristol",
    "Clackmannanshire",
    "Clwyd",
    "Conwy",
    "Cornwall/Scilly",
    "Cumbria",
    "Denbighshire",
    "Derbyshire",
    "Derry/Londonderry",
    "Devon",
    "Dorset",
    "Down",
    "Dumfries and Galloway",
    "Dunbartonshire",
    "Dundee",
    "Durham",
    "Dyfed",
    "East Ayrshire",
    "East Dunbartonshire",
    "East Lothian",
    "East Renfrewshire",
    "East Riding Yorkshire",
    "East Sussex",
    "Edinburgh",
    "England",
    "Essex",
    "Falkirk",
    "Fermanagh",
    "Fife",
    "Flintshire",
    "Glasgow",
    "Gloucestershire",
    "Greater London",
    "Greater Manchester",
    "Gwent",
    "Gwynedd",
    "Hampshire",
    "Hartlepool",
    "Hereford and Worcester",
    "Hertfordshire",
    "Highlands",
    "Inverclyde",
    "Inverness-Shire",
    "Isle of Man",
    "Isle of Wight",
    "Kent",
    "Kincardinshire",
    "Kingston Upon Hull",
    "Kinross-Shire",
    "Kirklees",
    "Lanarkshire",
    "Lancashire",
    "Leicestershire",
    "Lincolnshire",
    "Londonderry",
    "Merseyside",
    "Merthyr Tydfil",
    "Mid Glamorgan",
    "Mid Lothian",
    "Middlesex",
    "Monmouthshire",
    "Moray",
    "Neath & Port Talbot",
    "Newport",
    "Norfolk",
    "North Ayrshire",
    "North East Lincolnshire",
    "North Lanarkshire",
    "North Lincolnshire",
    "North Somerset",
    "North Yorkshire",
    "Northamptonshire",
    "Northern Ireland",
    "Northumberland",
    "Nottinghamshire",
    "Orkney and Shetland Isles",
    "Oxfordshire",
    "Pembrokeshire",
    "Perth and Kinross",
    "Powys",
    "Redcar and Cleveland",
    "Renfrewshire",
    "Rhonda Cynon Taff",
    "Rutland",
    "Scottish Borders",
    "Shetland",
    "Shropshire",
    "Somerset",
    "South Ayrshire",
    "South Glamorgan",
    "South Gloucesteshire",
    "South Lanarkshire",
    "South Yorkshire",
    "Staffordshire",
    "Stirling",
    "Stockton On Tees",
    "Suffolk",
    "Surrey",
    "Swansea",
    "Torfaen",
    "Tyne and Wear",
    "Tyrone",
    "Vale Of Glamorgan",
    "Wales",
    "Warwickshire",
    "West Berkshire",
    "West Dunbartonshire",
    "West Glamorgan",
    "West Lothian",
    "West Midlands",
    "West Sussex",
    "West Yorkshire",
    "Western Isles",
    "Wiltshire",
    "Wirral",
    "Worcestershire",
    "Wrexham",
    "York",
    "United States",
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
    "Uruguay",
    "Artigas",
    "Canelones",
    "Cerro Largo",
    "Colonia",
    "Durazno",
    "Flores",
    "Lavalleja",
    "Maldonado",
    "Montevideo",
    "Paysandú",
    "Rivera",
    "Rocha",
    "Salto",
    "Soriano",
    "Tacuarembó",
    "Treinta y Tres",
    "US Virgin Islands",
    "Saint Croix",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Wallis and Futuna",
    "Futuna",
    "Alofi",
    "Yemen",
    "Abyan",
    "Aden",
    "Al Bayda",
    "Al Hudaydah",
    "Al Jawf",
    "Al Mahrah",
    "Al Mahwit",
    "Amanat Al Asimaha",
    "Amran",
    "Dhale",
    "Dhamar",
    "Hadramaut",
    "Hajjah",
    "Ibb",
    "Lahij",
    "Ma'rib",
    "Raymah",
    "Sa'dah",
    "Sana'a",
    "Shabwah",
    "Socotra Archipelagob",
    "Taiz",
    "Zambia",
    "Copperbelt",
    "Luapula",
    "Lusaka",
    "Muchinga",
    "North-Western",
    "Zimbabwe",
    "Bulawayo",
    "Harare",
    "Manicaland",
    "Mashonaland Central",
    "Mashonaland East",
    "Mashonaland West",
    "Masvingo",
    "Matabeleland North",
    "Matabeleland South",
    "Midlands"
]